### ISSUE TITLE
Credit Card Number Format Incorrect

### ISSUE THREAD

**Issue by nilopmsft** [cbattlegear/SynapseDemoDataGenerator#1]
Credit card data for Rental Generation scenario will product normal credit numbers (4x4 with hypens) example. 

4530-2744-7254-0733

But also will create ones with no hyphens and only 13 numbers. Example

4488800160403

Would prefer all results to be the former format.

**Comment by cbattlegear** [comment]
This is an issue in Bogus directly, have filed an issue with them but will work around it for the time being.
